import { AuthProvider, Nav } from '@/components'
import { khandFont } from '@/lib/constants'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={khandFont.className}>
			<AuthProvider>
				<body className='bg-amber-50 text-lg text-amber-950'>
					<Nav />
					<div className='mx-auto max-w-7xl px-4 pt-3'>{children}</div>
				</body>
			</AuthProvider>
		</html>
	)
}
