import { Nav } from '@/components/nav'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			{/* <AuthProvider> */}
			<body className='bg-amber-50 text-gray-800'>
				<Nav />
				{children}
			</body>
			{/* </AuthProvider> */}
		</html>
	)
}
